-- Create a trigger that, when a new place is inserted with a non-null `rating`,
-- creates a corresponding review in `public.reviews` (place_id, user_id, rating)
-- and clears the `rating` stored on the `places` row.
--
-- Usage:
-- 1) Open the Supabase SQL editor (or connect as the DB owner) and run this file.
-- 2) Ensure the `reviews` table exists with at least columns: place_id, user_id, rating, created_at.
-- 3) If your `places.id` is generated automatically (serial/uuid), an AFTER INSERT trigger is used
--    so the new place id is available for the review insertion.

BEGIN;

CREATE OR REPLACE FUNCTION public.create_review_on_place_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_rating numeric;
BEGIN
  -- If no rating supplied, nothing to do
  v_rating := NEW.rating;
  IF v_rating IS NULL THEN
    RETURN NEW;
  END IF;

  -- Insert a review for the newly created place
  -- Expectation: `public.reviews` table exists and has columns (place_id, user_id, rating, created_at)
  INSERT INTO public.reviews (place_id, user_id, rating, created_at)
  VALUES (NEW.id, NEW.user_id, v_rating, now());

  -- Remove rating from the places row so the rating is only stored in reviews
  -- Use an UPDATE here (AFTER INSERT) to ensure NEW.id is available even if id is generated by default.
  UPDATE public.places
  SET rating = NULL
  WHERE id = NEW.id;

  RETURN NEW;
END;
$$;

-- Remove existing trigger if present, then create the AFTER INSERT trigger
DROP TRIGGER IF EXISTS trg_create_review_on_place_insert ON public.places;

CREATE TRIGGER trg_create_review_on_place_insert
AFTER INSERT ON public.places
FOR EACH ROW
EXECUTE FUNCTION public.create_review_on_place_insert();

COMMIT;

-- Notes / Caveats:
-- - Run this as a DB owner (or a role with sufficient privileges). The function is declared
--   SECURITY DEFINER so it will execute with the function owner's rights; on Supabase
--   the owner must be the DB owner (console-created functions will be owned by the executing role).
-- - If your `reviews` table has additional NOT NULL columns, adapt the INSERT accordingly.
-- - If you prefer the rating never be sent to the server at all, modify the client to stop
--   sending `rating` with the places insert; this trigger simply moves it into `reviews` and
--   clears it from the `places` row.
